### ISSUE TITLE
"mautic/theme-skyline": "4.0.2" causes issue

### ISSUE THREAD

**Issue by tijsdeboeck** [mautic/recommended-project#10]
I just got a composer dependency error:

`Root composer.json requires mautic/theme-skyline 4.0.2, found mautic/theme-skyline[dev-main, dev-features, 4.0.0-alpha1, ..., 4.x-dev] but it does not match the constraint`

mautic/theme-skyline version "4.0.2" doesn't exist it seems. When I changed the version to "^4.0" it did kinda work, as it found version "4.0.1".

**Comment by RCheesley** [comment]
Thanks for reporting this @tijsdeboeck - just got to the bottom of it I think. We had missed it from the GitHub Workflow and also there was an incorrect specification in the json file.

Here's the PR to fix the problem, I hope!

https://github.com/mautic/mautic/pull/10645

**Comment by tijsdeboeck** [comment]
Thanks for the update @RCheesley !

**Comment by RCheesley** [comment]
No problem!  If it fixes the problem for you please do leave a ✅  on the PR :)

**Comment by tijsdeboeck** [comment]
It seems that alexbusu beat me to it ;)

**Comment by dennisameling** [comment]
@tijsdeboeck this should be resolved now - could you please check if things are working on your side as well? 😊

**Comment by tijsdeboeck** [comment]
Hi @dennisameling just tested it, and it worked 🚀 
Thanks a lot!

I'll close this ticket now, as it's fixed 👍
