### ISSUE TITLE
Composer installed and get 500 error

### ISSUE THREAD

**Issue by Henry17888** [mautic/recommended-project#15]
I followed the [document](https://docs.mautic.org/en/setup/how-to-install-mautic/install-and-manage-mautic-with-composer) and run: composer create-project mautic/recommended-project:^4 mail.mydomain.com --no-interaction
After this, I set my webroot to docroot and visit mail.mydomain.com, then I get an error as below:
The site is currently offline due to encountering an error. If the problem persists, please contact the system administrator.
System administrators, check server logs for errors.
So I checked the error.log, and get this
error.log as below:
FastCGI sent in stderr: "PHP message: TypeError: Doctrine\DBAL\Configuration::setResultCacheImpl(): Argument #1 ($cacheImpl) must be of type Doctrine\Common\Cache\Cache, Symfony\Component\Cache\Adapter\ArrayAdapter given, called in /www/wwwroot/mail.mydomain.com/docroot/var/cache/prod/ContainerHwWzP2h/appAppKernelProdContainer.php on line 2317 - in file /www/wwwroot/mail.mydomain.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Configuration.php - at line 63" while reading response header from upstream, client: 1xxxx.xx.xxx, server: mail.mydomain.com, request: "GET /index.php/installer HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-80.sock:", host: "mail.mydomain.com", referrer: "https://mail.mydomain.com/index.php/installer"

my web environment as below:
Server: Nginx 1.21
PHP version: 8.0
Mysql: 5.7

On this server, I have another Mautic, which I installed a week ago with the same steps and runs correctly. 
So, please kindly help to advise how to solve it.

**Comment by mollux** [comment]
@Henry17888  there is indeed an issue that popped up a couple of days ago due to an update in one of the dependencies of mautic (the doctrine/doctrine-bundle dependency).

We are working on this in mautic/mautic#11053, but you could test out the fix with following steps in the meantime

execute following command in the root of your project.

```
composer require doctrine/doctrine-bundle ~2.5.0
```
This should give output similar to this:

```
bash-5.1# composer2 require doctrine/doctrine-bundle ~2.5.0
./composer.json has been updated
Running composer update doctrine/doctrine-bundle
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 1 update, 0 removals
  - Downgrading doctrine/doctrine-bundle (2.6.1 => 2.5.7)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading doctrine/doctrine-bundle (2.6.1 => 2.5.7): Extracting archive
```

can you confirm this solved this issue?

**Comment by Henry17888** [comment]
@mollux Thank you so much. It works well.
When I install Mautic in step 2, I can't connect my database with php8(error: An error occurred while attempting to add default data: There is no active transaction), so I change the PHP version to 7.4, then I can install it completely. I don't know what's wrong with it, it may be my environmental question.
Anyway, I can run it now. Thank you.

**Comment by mollux** [comment]
@Henry17888 

thanks for confirming.

PHP 8 support for Mautic is indeed not complete, and it's recommended to stay on 7.4 until there 
We are actively working on getting it compatible

**Comment by Henry17888** [comment]
@mollux My pleasure. Thank you for your kindly support.

**Comment by RCheesley** [comment]
Fixed with https://github.com/mautic/mautic/pull/11053 🎉
