### ISSUE TITLE
Mautic not installable with php8.0 or php8.1

### ISSUE THREAD

**Issue by christian-pletz** [mautic/recommended-project#17]
Mautic is not installable with php version 8.0 or 8.1

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofsymfony/oauth-server-bundle dev-doctrine-fix requires php ^5.5|^7.0 -> your php version (8.0.18) does not satisfy that requirement.
    - mautic/core-lib 4.2.2 requires friendsofsymfony/oauth-server-bundle dev-doctrine-fix -> satisfiable by friendsofsymfony/oauth-server-bundle[dev-doctrine-fix].
    - Root composer.json requires mautic/core-lib 4.2.2 -> satisfiable by mautic/core-lib[4.2.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

**Comment by RCheesley** [comment]
Hi @christian-pletz , we know this. Mautic is not yet compatible with PHP8. We are doing a lot of work to make it so but it's a pretty significant job.

Please check the requirements: https://www.mautic.org/download/requirements for more details.

Keep an eye on the PR here: https://github.com/mautic/mautic/pull/9969 and do contribute if you're able - we're going to be doing a bunch of work Monday-Wednesday in our Community Sprint.
