### ISSUE TITLE
Root composer.json requires mautic/theme-paprika 4.4.6, found mautic/theme-paprika ...

### ISSUE THREAD

**Issue by ashishbhatiya18** [mautic/recommended-project#34]
but it does not match the constraint.

Can someone please include 4.4.6 version on packagist for mautic/theme-paprika?

**Comment by RCheesley** [comment]
It's tagged already, so it should be there! I'll dig into it a bit later.

**Comment by RCheesley** [comment]
@mollux any ideas on this? The git split worked and the tag is present on the repo.

**Comment by campaigncenter** [comment]
@ashishbhatiya18 same problem here. As a workaround I have removed parika from my composer.json and was able to proceed.

**Comment by RCheesley** [comment]
Hi folks!

Could you please try checking now? I've just logged into Packagist and manually updated the package. I don't know why it didn't automatically get the new tag - but hopefully this fixes it!

**Comment by campaigncenter** [comment]
@RCheesley Works perfectly. Thank you!

**Comment by RCheesley** [comment]
Great! Literally no idea why Packagist decided not to update that one repo but at least we know where to troubleshoot if it happens again! 😅
