### ISSUE TITLE
Tightenco/collect version issue .......mautic/sealos require 5.6 while mautic/core-lib 4.4.9 requires v8.16.0

### ISSUE THREAD

**Issue by Omkarc284** [mautic/recommended-project#45]
mautic/mautic-saelos-bundle[2.0, ..., 2.1] require tightenco/collect ^5.6 -> found tightenco/collect[v5.6.0, ..., v5.8.38] but the package is fixed to v8.16.0 (lock file version) by a partial update and that version does not match.
and mautic core lib 4.4.9 requires tightenco/collect v8.16.0 how to resolve this dependency issue?
i guess its something from the maintainer's side and only they can resolve it

**Comment by Omkarc284** [comment]
![error](https://github.com/mautic/mautic-saelos-bundle/assets/77777642/25d3fcdb-7627-432c-94b2-ed47b5cb89b5)

**Comment by RCheesley** [comment]
Hi @Omkarc284 per the comment on Slack, this plugin has been deprecated for a long time, but the Recommended Project documentation hasn't been updated to replace it with another plugin.

We're just making a PR to fix this.

Thanks for flagging it up!

**Comment by Omkarc284** [comment]
Please mention the solution to this as I need it urgently how can i proceed?

**Comment by escopecz** [comment]
The solution is simply do not call this command:
```
composer require mautic/mautic-saelos-bundle:~2.0
```
mentioned in the readme. It's just an example how you would install a Mautic plugin. You should not execute it if you don't want to install the Saelos plugin.

If you have installed it before, you can simply remove it with:
```
composer remove mautic/mautic-saelos-bundle
````

**Comment by mollux** [comment]
the `mautic/mautic-saelos-bundle`  was removed from the readme, closing this issue
