### ISSUE TITLE
cant send email even test email 

### ISSUE THREAD

**Issue by giorgigadrani** [mautic/recommended-project#74]
when we want to send email we receive  this error : 
![Screenshot 2024-05-14 112445](https://github.com/mautic/recommended-project/assets/169656905/1c584471-ae26-4fa1-85b0-5222199e05af)
Using currently saved DSN: smtp://no-reply%40money4you.financial:SECRET@mail.money4you.financial:465
Failed to authenticate on SMTP server with username "no-reply@money4you.financial" using the following authenticators: "LOGIN", "PLAIN". Authenticator "LOGIN" returned "Expected response code "235" but got code "535", with message "535 Incorrect authentication data".". Authenticator "PLAIN" returned "Expected response code "235" but got code "535", with message "535 Incorrect authentication data".".

**Comment by escopecz** [comment]
It doesn't seem like a bug but more as a misconfiguration of the email credentials. Please send this error message and DSN to your email provider and ask what's wrong with it.
