### ISSUE TITLE
configuration page is not loading or load very slow 

### ISSUE THREAD

**Issue by giorgigadrani** [mautic/recommended-project#75]
we are trying to change email setting but the problem is the configuration page on mautic is not loadin
![Screenshot 2024-05-14 123417](https://github.com/mautic/recommended-project/assets/169656905/df5400ec-9978-4241-bcce-033dcbefd4e5)
g

**Comment by escopecz** [comment]
I assume this is a continuation of https://github.com/mautic/recommended-project/issues/74. You may have an error in your logs. Please check https://docs.mautic.org/en/5.x/troubleshooting/troubleshooting.html where are some troubleshooting tips and how to get to the log messages. Paste the error logs here so we could help you.
