### ISSUE TITLE
I need help filing up the email DSN 

### ISSUE THREAD

**Issue by giorgigadrani** [mautic/recommended-project#76]
HI , I am trying to fill-up the email DSN setting but i cannot fill the up correctly I don't know to right outputs 
the DSN Scheme what should be i saw the article on mautic but i didn't understand it  
![Screenshot 2024-05-14 150001](https://github.com/mautic/recommended-project/assets/169656905/7ce235a5-751c-4d32-bed5-49415b3aec27)

**Comment by RCheesley** [comment]
Hi there, 

Please review the documentation here: https://docs.mautic.org/en/5.x/configuration/settings.html#email-settings

If you get stuck, please ask for support at https://forum.mautic.org as that's where we help people who need assistance with configuring Mautic. Thanks so much!

**Comment by escopecz** [comment]
Please, provide screen recording of what you are doing to the form thread and link it here. The validation error doesn't match the value you have in the scheme field.
