### ISSUE TITLE
we are not receiving test emails on Gmail and yahoo only mautic is sending test emails trough webmail's  

### ISSUE THREAD

**Issue by shimamlkz** [mautic/recommended-project#79]
we are not receiving test emails on Gmail and yahoo only mautic 
![Screenshot 2024-05-23 111242](https://github.com/mautic/recommended-project/assets/169876506/c8269a57-4549-481e-b474-871941c75305)
is sending test emails trough webmail's  only

**Comment by escopecz** [comment]
See https://github.com/mautic/recommended-project/issues/76#issuecomment-2109996015

**Comment by shimamlkz** [comment]
now we just can send test mails trough webmail's but still not available to send gmail  test mails 
i send a screen recording from y mautic   

https://github.com/mautic/recommended-project/assets/169876506/083b9dc6-0e05-496d-8114-20da779bab74

**Comment by escopecz** [comment]
Please check the logs when it happens. Go to the System Info in the admin menu (cog icon) and see the latest logs there.

**Comment by shimamlkz** [comment]
we get the massage limit error 
but we don't know how to fix it 

![Screenshot 2024-05-28 104627](https://github.com/mautic/recommended-project/assets/169876506/cab04e0f-3f09-454d-8df6-e4774c5f5e25)

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by escopecz** [comment]
@shimamlkz please do what Ruth suggested and link the forum post here for others to follow the discussion. But the error message means in that you are calling probably by cron command `mautic:messages:send --message-limit...` but this `--message-limit` parameter doesn't exist in that command.
