### ISSUE TITLE
Web installer fails after step 1

### ISSUE THREAD

**Issue by mickaelperrin** [mautic/recommended-project#8]
Hi,

I installed mautic using composer.

When I try to install it using the web installer I got the following issue after validating step 1:

```
mautic.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Notice: require(): Failed opening required '/src/docroot/var/cache/prod/ContainerIAAb2Rd/getTranslation_Loader_PhpService.php' (include_path='.:/usr/local/lib/php:/src/misc') - in file /src/docroot/var/cache/prod/ContainerIAAb2Rd/appAppKernelProdContainer.php - at line 2226 []
```

When I look into the `/src/docroot/var/cache/prod` folder after the error, it's empty.

I tried to warmup cache using the cli, files are created but the error continues and files got deleted.

Any idea ?

**Comment by nickveenhof** [comment]
Can you post the specifics of your system setup and steps to reproduce? Thanks!

**Comment by mollux** [comment]
closing stale issue
