### ISSUE TITLE
When I try to update mautic,something like this opens up

### ISSUE THREAD

**Issue by giorgigadrani** [mautic/recommended-project#81]
![IMG_5577](https://github.com/mautic/recommended-project/assets/169656905/17cfa79d-a21d-4e82-a78c-233d4604ee7c)

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)
