### ISSUE TITLE
Wrong versions in release 4.4.13

### ISSUE THREAD

**Issue by PatrickJenkner** [mautic/recommended-project#89]
The release for 4.4.13 (and I think also some older 4.4.x's) has the wrong version for `mautic/core-composer-scaffold` and `mautic/core-project-message`: It should be "4.x-dev" instead of "4.4.13"

**Comment by RCheesley** [comment]
Yes, we've had reports of that already - see https://mautic.slack.com/archives/C01E8F6T2HM/p1727945563556779. We need to fix & re-tag the repo.

**Comment by escopecz** [comment]
Here is the fix for the 4.4.13 release https://github.com/mautic/recommended-project/pull/92

**Comment by escopecz** [comment]
4.4.13 release was fixed. Please give it a try.
