### ISSUE TITLE
Directory structure exposes everything to docroot ?

### ISSUE THREAD

**Issue by mickaelperrin** [mautic/recommended-project#9]
Hi again,

I have some interrogations regarding the directory structure of the project.

Everything is scaffolded in a directory which has been renamed in the history of the project from public to docroot.

I don't get the point why everything is exposed through the web server docroot and why there isn't a public folder with the only available php entry points and static assets like in any symfony project ?

This is not maybe the right place to talk that. Not sure where to post.

**Comment by nickveenhof** [comment]
Hi! Good question. This project is taking an iterative approach. In the original Mautic the vendor folder for composer dependencies is accessible to the webserver. In this project it is not. To make that more secure, more severe changes to core Mautic are needed. We are welcoming your help! :-)
